version: "3.3"

volumes:
  mysql_data: {}

services:
  mysqldb:
    image: mysql:8.0
    volumes: 
      - ./mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - foodapi-network
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pedidos
      MYSQL_USER: pedidos
      MYSQL_PASSWORD: pedidos
  springboot-app:
    image: springboot-app
    networks:
      - foodapi-network
    environment:
      DATASOURCE_URL: jdbc:mysql://mysqldb:3306/pedidos
    build: .
    depends_on:
      - mysqldb
    ports:
      - "8080:8080"
networks:
  foodapi-network: