apiVersion: v1
kind: Service
metadata:
  name: svc-db-food
  labels:
    app: svc-db-food
spec:
  ports:
  - port: 3306
    name: svc-db-food
  clusterIP: None
  selector:
    app: statefulset-db-food