# Ref: https://www.docker.com/blog/docker-v2-github-action-is-now-ga/
name: CI/CD

on:
  push:
    branches:
      - feat/apply-new-version
  # pull_request:
  #   branches:
  #     - main
  workflow_dispatch:

jobs:
  build-docker-image:
    runs-on: ubuntu-latest

    env:
      BUILD_VERSION: ${{ github.event.inputs.app_image_version || github.sha }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Load environment variables
        uses: thaind0/envfile@v1
        with:
          secrets: ${{ toJSON(secrets) }}

      - name: Setup Docker
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.yml
          # build-args: |
          #   APPLICATION_VERSION=${{ env.BUILD_VERSION }}
          platforms: linux/amd64
          push: true
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.IMAGE_NAME }}:cache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.IMAGE_NAME }}:cache,mode=max
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.IMAGE_NAME }}:${{ env.BUILD_VERSION }}

  apply-new-version:
    runs-on: ubuntu-latest
    needs: build-docker-image

    env:
      BUILD_VERSION: ${{ github.event.inputs.app_image_version || github.sha }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Clone Terraform Config Repository
        run: git clone https://github.com/ALFAC-Org/food-cloud-infra.git

      - name: Load environment variables
        uses: thaind0/envfile@v1
        with:
          secrets: ${{ toJSON(secrets) }}
          file: food-cloud-infra/.env

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init -reconfigure
        working-directory: food-cloud-infra

      - name: Terraform Validate
        run: terraform validate
        working-directory: food-cloud-infra

      - name: Terraform Plan
        run: bash terraform.sh plan
        working-directory: food-cloud-infra

      - name: Terraform Apply
        run: bash terraform.sh apply -auto-approve
        working-directory: food-cloud-infra
