name: Coverage

on: [push, pull_request]

# Descomente se precisar de uma nova branch para fazer alterações/testes
#on:
#  push:
#    branches:
#      - feat/add-coverage-info

jobs:
  coverage:
    name: Coverage
    uses: ALFAC-Org/github-workflows/.github/workflows/coverage.yaml@main  
    secrets: inherit
    with:
      java_version: "17"
      minimum_coverage: "0"
      coverage_results_path: "food-main/target/jacoco-report/jacoco.xml"
      jacoco_csv_file: "food-main/target/jacoco-report/jacoco.csv"
