name: Coverage

on: [push, pull_request]

jobs:
  coverage:
    runs-on: ubuntu-latest
    container: maven:3.8.1-openjdk-17-slim

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and test with coverage
        run: mvn clean verify

#       TODO: exibir o coverage no github
#      - name: Upload coverage report
#        uses: actions/download-artifact@v4
#        with:
#          name: coverage-report
#          path: food-main/target/jacoco-report
